services:

  db:
    image: 'postgres:18'
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=avt
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U compose-postgres -d avt" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: 'redis:8.6'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  api:
    build:
      context: ./backend
    image: backend
    volumes:
      - uploads:/uploads
    depends_on:
      db:
        condition: service_healthy
    command: python run_api.py

  worker_high:
    image: backend
    volumes:
      - uploads:/uploads
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A app.worker.video_worker worker --loglevel=INFO -Q high

  worker_low:
    image: backend
    volumes:
      - uploads:/uploads
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A app.worker.video_worker worker --loglevel=INFO -Q high,low

  frontend:
    build: 
      context: ./frontend
    depends_on:
      - api
    ports:
      - ${PORT_NUMBER}:80

volumes:
  uploads:
  db-data: